"""
Newsletter HTML + Plain Text Generator (Epic 15).

Takes a CurationResult and generates a formatted newsletter using Gemini Flash.
Output: {html: str, plain_text: str, subject: str}
"""

import logging
import os
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# Lazy import to support both package and flat imports (Cloud Functions)
_get_client = None
_GenerationConfig = None


def _ensure_llm_imports():
    global _get_client, _GenerationConfig
    if _get_client is None:
        try:
            from src.llm import get_client
            from src.llm.base import GenerationConfig
        except ImportError:
            from llm import get_client
            from llm.base import GenerationConfig
        _get_client = get_client
        _GenerationConfig = GenerationConfig


NEWSLETTER_GENERATOR_MODEL = os.getenv("NEWSLETTER_GENERATOR_MODEL", "gemini-3-flash-preview")

try:
    from src.summary.delivery import _markdown_to_html
except ImportError:
    from delivery import _markdown_to_html

GENERATOR_SYSTEM_PROMPT = """\
You are a tech newsletter writer for a senior software engineering audience.

Write in a clear, analytical, slightly informal English tone. No fluff, no filler.
Each section should provide genuine value: insights, not just summaries.
Use Obsidian callout syntax for highlighted insights: > [!tip] Title followed by content lines starting with >.
"""

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{subject}</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 680px; margin: 40px auto; padding: 0 20px; background: #fafafa; color: #1a1a1a; line-height: 1.65; }}
  h1 {{ font-size: 1.7em; margin-bottom: 0.1em; color: #111; }}
  .subtitle {{ font-size: 1.0em; color: #6b7280; margin-top: 0; margin-bottom: 1.5em; }}
  h2 {{ font-size: 1.3em; margin-top: 2em; border-bottom: 1px solid #e0e0e0; padding-bottom: 0.3em; color: #222; }}
  h3 {{ font-size: 1.05em; color: #374151; margin-top: 1.2em; }}
  a {{ color: #2563eb; }}
  ul, ol {{ padding-left: 1.5em; margin: 0.6em 0; }}
  li {{ margin-bottom: 0.4em; }}
  blockquote {{ border-left: 3px solid #6366f1; margin: 1.2em 0; padding: 0.6em 1em; background: #f5f3ff; border-radius: 4px; }}
  blockquote strong {{ color: #4f46e5; }}
  hr {{ border: none; border-top: 1px solid #e0e0e0; margin: 2em 0; }}
  p {{ margin: 0.8em 0; }}
  .footer {{ margin-top: 2.5em; padding-top: 1em; border-top: 1px solid #e0e0e0; font-size: 0.8em; color: #9ca3af; }}
  @media (max-width: 480px) {{ body {{ margin: 16px auto; padding: 0 14px; }} }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="subtitle">{date_range}</p>
{body}
<div class="footer">Generated by kx-hub · {date}</div>
</body>
</html>
"""


def generate_newsletter(
    curation_result: "CurationResult",
    period: dict,
    relationships: list | None = None,
    previous_issue: dict | None = None,
    source_urls: dict | None = None,
    author_lookup: dict | None = None,
) -> dict:
    """
    Generate newsletter HTML and plain text from a CurationResult.

    Args:
        curation_result: Curated sources and hot news.
        period: {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}
        relationships: Cross-source relationships with URLs.
        previous_issue: {"subject": ..., "period_start": ..., "period_end": ...}
        source_urls: {source_id: url} for connection link resolution.
        author_lookup: {url: author} to enrich sources without author set.

    Returns:
        dict with keys: html, plain_text, subject
    """
    _ensure_llm_imports()

    start = period.get("start", "")
    end = period.get("end", "")
    date_range = _format_date_range(start, end)
    title = "Christian's View on Trends in AI & Software"
    subject = f"{title} — {date_range}"

    prompt = _build_generator_prompt(
        curation_result,
        period,
        relationships or [],
        previous_issue=previous_issue,
        source_urls=source_urls,
        author_lookup=author_lookup,
    )

    client = _get_client(NEWSLETTER_GENERATOR_MODEL)
    config = _GenerationConfig(temperature=0.6, max_output_tokens=4096)
    response = client.generate(prompt, config=config, system_prompt=GENERATOR_SYSTEM_PROMPT)

    body_text = response.text.strip()

    # Build HTML
    html_body = _markdown_to_html(body_text)
    html = _HTML_TEMPLATE.format(
        subject=subject,
        title=title,
        date_range=date_range,
        body=html_body,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    )

    plain_text = _build_plain_text(subject, curation_result, body_text)

    logger.info(f"Newsletter generated: {len(html)} chars HTML, {len(plain_text)} chars plain text")

    return {"html": html, "plain_text": plain_text, "subject": subject, "title": title}


def _format_date_range(start: str, end: str) -> str:
    """Format '2026-03-01' to '2026-03-07' as '1.3.26 – 7.3.26'."""
    try:
        from datetime import datetime as dt
        s = dt.strptime(start, "%Y-%m-%d")
        e = dt.strptime(end, "%Y-%m-%d")
        sy = str(s.year)[2:]
        ey = str(e.year)[2:]
        return f"{s.day}.{s.month}.{sy} \u2013 {e.day}.{e.month}.{ey}"
    except Exception:
        return f"{start} \u2013 {end}"


def _is_valid_external_url(url: str) -> bool:
    """Return True only for genuine external HTTP URLs (not readwise.io, mailto:, empty)."""
    return (
        bool(url)
        and url.startswith("http")
        and "readwise.io" not in url
        and "mailto:" not in url
    )


_REL_TYPE_HINTS = {
    "extends": "deepens the point of",
    "contradicts": "stands in contrast to",
    "supports": "supports the view of",
    "applies to": "applies the idea of",
    "applies_to": "applies the idea of",
    "relates to": "connects thematically to",
    "relates_to": "connects thematically to",
}


def _build_generator_prompt(
    curation_result: "CurationResult",
    period: dict,
    relationships: list,
    previous_issue: dict | None = None,
    source_urls: dict | None = None,
    author_lookup: dict | None = None,
) -> str:
    """Build the LLM prompt for newsletter body generation."""
    lines = [
        f"Generate a tech newsletter for the week of {period.get('start')} to {period.get('end')}.",
        "",
    ]

    # Previous issue context
    if previous_issue and previous_issue.get("subject"):
        lines += [
            "=== PREVIOUS ISSUE ===",
            f"Subject: {previous_issue['subject']}",
            f"Period: {previous_issue.get('period_start', '')} to {previous_issue.get('period_end', '')}",
            "",
        ]

    # Hot news
    if curation_result.hot_news:
        lines += ["=== HOT NEWS (from ADK agent) ==="]
        for item in curation_result.hot_news:
            lines.append(f"- [{item.title}]({item.url}): {item.summary}")
        lines.append("")

    # Sources with author info
    lines += [
        "=== SOURCES (curated, with authors) ===",
        "Group these into 2-3 categories using ### subheadings:",
        "  - ### AI & Process  (AI, LLM, ML, tooling, automation, agents)",
        "  - ### Software Engineering  (architecture, languages, dev practices, APIs)",
        "  - ### Beyond the Code  (business, leadership, science, product, other)",
        "If a category would have <2 sources, merge it into the closest other category.",
        "",
    ]
    for src in curation_result.filtered_sources:
        author = src.author or (author_lookup or {}).get(src.url, "")
        author_note = f" by {author}" if author and author not in ("Unknown", "") else ""
        title_part = f"[{src.title}]({src.url})" if src.url else src.title
        lines.append(f"- {title_part}{author_note} ({src.source_type}): {src.summary}")

    # Connections with URLs
    if relationships:
        lines += [
            "",
            "=== CONNECTIONS ===",
            "Use these when writing connections (include the actual hyperlinks):",
        ]
        for rel in relationships[:8]:
            hint = _REL_TYPE_HINTS.get(rel.get("relationship_type", "").lower(), "connects to")
            from_url = (source_urls or {}).get(rel.get("from_source_id", ""), "")
            target_url = rel.get("target_readwise_url") or rel.get("target_source_url", "")
            # Filter out internal/invalid URLs (readwise.io, mailto:, empty)
            if not _is_valid_external_url(from_url):
                from_url = ""
            if not _is_valid_external_url(target_url):
                target_url = ""
            from_part = (
                f"[{rel['from_title']}]({from_url})" if from_url
                else f"\"{rel['from_title']}\""
            )
            target_part = (
                f"[{rel.get('target_title', 'Unknown')}]({target_url})" if target_url
                else f"\"{rel.get('target_title', 'Unknown')}\""
            )
            lines.append(f"- {from_part} {hint} {target_part}: {rel.get('explanation', '')}")

    # Instructions
    lines += [
        "",
        "=== INSTRUCTIONS ===",
        "Write the newsletter body in Markdown. Follow this exact structure:",
        "",
        "1. Personal intro (2-3 sentences, NO section header).",
        "   Start with 'Hi everyone, ...'",
        "   Tone: warm, personal, slightly humorous.",
        "   If PREVIOUS ISSUE is provided, briefly reference last week's topic.",
        "   After the intro sentences, add the ONE overarching insight or thesis as a callout box:",
        "   > [!tip] This week's takeaway",
        "   > One sharp sentence — the thing you'd tell a colleague over coffee.",
        "",
        "2. ## Hot in AI & Software This Week",
        "   1-2 compact sentences summarizing the overall theme or mood of this week's news.",
        "   Then each news item as a bullet. REQUIRED format per item:",
        "   `- [Title](url) — one sentence of context.`",
        "   The URL MUST come from the HOT NEWS section above. Never drop the link.",
        "   Skip this section entirely if no HOT NEWS items were provided.",
        "",
        "3. ## What I've Been Reading",
        "   Use 2-3 category ### subheadings (AI & Process / Software Engineering / Beyond the Code).",
        "   If a category has <2 sources, merge it into the closest other one.",
        "",
        "   For EACH category:",
        "   a) 2-3 sentences of synthesis — describe the trend or tension across the sources.",
        "      Write an opinion, not just a summary.",
        "   b) Compact source list — one bullet per source:",
        "      If a URL is given: `- [Title](url) · Author — one sharp sentence`",
        "      If NO URL is given (plain title in SOURCES): `- Title · Author — one sharp sentence`",
        "      NEVER invent or guess URLs. Only hyperlink when a real URL was provided.",
        "   c) Connections callout (if CONNECTIONS data is available for this group):",
        "      Format EXACTLY like this:",
        "      > [!example] Connections",
        "      > - Deepens the point with [Target Title](target_url): explanation",
        "      > - Stands in contrast to [Other Title](other_url): explanation",
        "      Use real URLs from the CONNECTIONS section above. Max 2-3 per group.",
        "",
        "Output ONLY the newsletter body in Markdown. No subject line, no sign-off.",
    ]

    return "\n".join(lines)


def _build_plain_text(subject: str, curation_result: "CurationResult", body_text: str) -> str:
    """Build plain text version of the newsletter."""
    lines = [
        subject,
        "=" * len(subject),
        "",
        body_text,
        "",
        "---",
        "Generated by kx-hub",
    ]
    return "\n".join(lines)
