"""
Newsletter HTML + Plain Text Generator (Epic 15).

Takes a CurationResult and generates a formatted newsletter using Gemini Flash.
Output: {html: str, plain_text: str, subject: str}
"""

import logging
import os
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# Lazy import to support both package and flat imports (Cloud Functions)
_get_client = None
_GenerationConfig = None


def _ensure_llm_imports():
    global _get_client, _GenerationConfig
    if _get_client is None:
        try:
            from src.llm import get_client
            from src.llm.base import GenerationConfig
        except ImportError:
            from llm import get_client
            from llm.base import GenerationConfig
        _get_client = get_client
        _GenerationConfig = GenerationConfig


NEWSLETTER_GENERATOR_MODEL = os.getenv("NEWSLETTER_GENERATOR_MODEL", "gemini-2.0-flash")

GENERATOR_SYSTEM_PROMPT = """\
You are a tech newsletter writer for a senior software engineering audience.

Write in a clear, analytical, slightly informal English tone. No fluff, no filler.
Each section should provide genuine value: insights, not just summaries.
"""

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{subject}</title>
<style>
  body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #ffffff; color: #1a1a1a; line-height: 1.6; }}
  h1 {{ font-size: 1.5em; color: #111; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5em; }}
  h2 {{ font-size: 1.2em; color: #374151; margin-top: 2em; }}
  .source-item {{ margin-bottom: 1.2em; padding: 12px; background: #f9fafb; border-left: 3px solid #6366f1; border-radius: 4px; }}
  .source-item a {{ color: #4f46e5; text-decoration: none; font-weight: 600; }}
  .source-item a:hover {{ text-decoration: underline; }}
  .source-meta {{ font-size: 0.85em; color: #6b7280; margin-bottom: 0.4em; }}
  .hot-news-item {{ margin-bottom: 1em; }}
  .hot-news-item a {{ color: #dc2626; font-weight: 600; }}
  .takeaway {{ background: #fef3c7; border-left: 3px solid #f59e0b; padding: 12px; border-radius: 4px; margin: 1.5em 0; }}
  .footer {{ margin-top: 2em; padding-top: 1em; border-top: 1px solid #e5e7eb; font-size: 0.8em; color: #9ca3af; }}
  @media (max-width: 480px) {{ body {{ padding: 12px; }} }}
</style>
</head>
<body>
<h1>{subject}</h1>
{body}
<div class="footer">Generated by kx-hub · {date}</div>
</body>
</html>
"""


def generate_newsletter(curation_result: "CurationResult", period: dict) -> dict:
    """
    Generate newsletter HTML and plain text from a CurationResult.

    Returns:
        dict with keys: html, plain_text, subject
    """
    _ensure_llm_imports()

    start = period.get("start", "")
    end = period.get("end", "")
    subject = f"Tech Reads: {_format_date_range(start, end)}"

    prompt = _build_generator_prompt(curation_result, period)

    client = _get_client(NEWSLETTER_GENERATOR_MODEL)
    config = _GenerationConfig(temperature=0.6, max_output_tokens=4096)
    response = client.generate(prompt, config=config, system_prompt=GENERATOR_SYSTEM_PROMPT)

    body_text = response.text.strip()

    # Build HTML
    html_body = _text_to_html_sections(curation_result, body_text)
    html = _HTML_TEMPLATE.format(
        subject=subject,
        body=html_body,
        date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
    )

    plain_text = _build_plain_text(subject, curation_result, body_text)

    logger.info(f"Newsletter generated: {len(html)} chars HTML, {len(plain_text)} chars plain text")

    return {"html": html, "plain_text": plain_text, "subject": subject}


def _format_date_range(start: str, end: str) -> str:
    """Format '2026-03-01' to '2026-03-07' as 'Mar 1-7, 2026'."""
    try:
        from datetime import datetime as dt
        months = {1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",
                  7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"}
        s = dt.strptime(start, "%Y-%m-%d")
        e = dt.strptime(end, "%Y-%m-%d")
        return f"{months[s.month]} {s.day}\u2013{e.day}, {e.year}"
    except Exception:
        return f"{start} \u2013 {end}"


def _build_generator_prompt(curation_result: "CurationResult", period: dict) -> str:
    """Build the LLM prompt for newsletter body generation."""
    lines = [
        f"Generate a concise, high-value tech newsletter for the week of {period.get('start')} to {period.get('end')}.",
        "",
        "## What I've Been Reading",
        "Write 2-3 sentences of synthesis connecting the reading themes. Then list each source with a 1-sentence insight.",
        "",
        "Sources:",
    ]
    for src in curation_result.filtered_sources:
        lines.append(f"- [{src.title}]({src.url}) ({src.source_type}): {src.summary}")

    lines.append("")
    lines.append("## Hot in AI & Software This Week")
    lines.append("Brief intro sentence. Then list each news item with 1-sentence context.")
    lines.append("")
    if curation_result.hot_news:
        lines.append("News items:")
        for item in curation_result.hot_news:
            lines.append(f"- [{item.title}]({item.url}): {item.summary}")
    else:
        lines.append("(No curated news items available this week — skip this section or note 'no major news'.)")

    lines.append("")
    lines.append("## One Key Takeaway")
    lines.append("A single actionable or thought-provoking insight from this week's reading. 2-4 sentences.")
    lines.append("")
    lines.append("Output ONLY the newsletter body in Markdown. No subject line, no greeting, no sign-off.")

    return "\n".join(lines)


def _text_to_html_sections(curation_result: "CurationResult", body_text: str) -> str:
    """Convert markdown body + structured data into HTML sections."""
    import re

    # Convert markdown to simple HTML
    html = body_text
    # Headers
    html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
    # Bold
    html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
    # Links
    html = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'<a href="\2">\1</a>', html)
    # List items
    html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
    # Paragraphs
    paragraphs = html.split('\n\n')
    html_parts = []
    for p in paragraphs:
        p = p.strip()
        if not p:
            continue
        if p.startswith('<h') or p.startswith('<li>'):
            if '<li>' in p:
                html_parts.append(f'<ul>{p}</ul>')
            else:
                html_parts.append(p)
        else:
            html_parts.append(f'<p>{p}</p>')

    return '\n'.join(html_parts)


def _build_plain_text(subject: str, curation_result: "CurationResult", body_text: str) -> str:
    """Build plain text version of the newsletter."""
    lines = [
        subject,
        "=" * len(subject),
        "",
        body_text,
        "",
        "---",
        "Generated by kx-hub",
    ]
    return "\n".join(lines)
